# Generated by Django 3.0.3 on 2020-03-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='images',
            field=models.ImageField(default='', upload_to='newapp/static/images'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
