# Generated by Django 3.0.3 on 2020-03-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20200315_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_name',
            new_name='user_name1',
        ),
    ]
